version: "3"

services:
  web:
    container_name: web-container
    build:
      context: ./docker/php/
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - ./Docker/php/php.ini:/etc/php.ini
      - ./Docker/httpd/my-vhost.conf:/etc/httpd/conf.d/my-vhost.conf
    ports:
      - 80:80
  db:
    image: mariadb:5.5.64-trusty
    container_name: db-container
    environment:
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - ./Docker/mariadb/init:/docker-entrypoint-initdb.d
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma-container
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=password
    links:
      - db
    ports:
      - 8080:80
    volumes:
      - /sessions
