version: "3"

services:
  https-portal:
    image: steveltn/https-portal:1
    container_name: https-container
    ports:
      - '443:443'
    environment:
      DOMAINS: 'localhost -> http://web:80'
      STAGE: local